name: Main

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  checks:
    name: Checks
    uses: ./.github/workflows/checks.yml
    with:
      docker-login: true
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  archguard:
    name: ArchGuard
    uses: ./.github/workflows/archguard.yml
    secrets:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
