name: PR

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  checks:
    name: Checks
    uses: ./.github/workflows/checks.yml
    with:
      docker-login: ${{ github.event.pull_request.user.login == github.repository_owner }}
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  archguard:
    name: ArchGuard
    if: github.event.pull_request.user.login == github.repository_owner
    uses: ./.github/workflows/archguard.yml
    secrets:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
